# Generated by Django 4.1.5 on 2023-01-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraph5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
