# Generated by Django 4.1.5 on 2023-01-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_tag_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Article_images'),
        ),
    ]
