# Generated by Django 4.1.5 on 2023-01-11 03:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_article_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paragraph1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
