# Generated by Django 4.1.5 on 2023-01-11 03:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_alter_author_paragraph1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='paragraph1',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paragraph3',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paragraph5',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
